server:
    port: 5020
    servlet:
        context-path: /v1
        session:
            timeout: 7200s
    tomcat:
        basedir: /data/logs/access
        accesslog:
            enabled: true
            pattern: '%t %a "%r" %s (%D ms)'

logging:
    level:
        root: info
    path: /data/logs

spring:
    setvlet:
        multipart:
            max-file-size: 15M
    #支持通过CGLIB方式代理
    aop:
        proxy-target-class: true
    mail:
        host: smtp.mxhichina.com
        username:
        password:
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 25000

mybatis:
    typeAliasesPackage: com.cold.framework.dao.model
    mapperLocations: classpath:mapper/*Mapper.xml
    configLocation: classpath:mybatis-config.xml
    checkConfigLocation: true

mapper:
    not-empty: false
    identity: MYSQL
    mappers:
        - com.cold.framework.dao.util.ColdMapper

rabbitmq:
    exchanges:
        collection-topic:
            name: collection-topic
            type: topic
            durable: true
        warn-fanout:
            name: warn-fanout
            type: fanout
            durable: true
    queues:
        collection-in:
            name: collection-in
        collection-out:
            name: collection-out
        message:
            name: warn-message
        email:
            name: warn-email
    bindings:
        collection-topic:
            - collection-in
            - collection-out
        warn-fanout:
            - warn-message
            - warn-email


---
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/
        username:
        password:
        tomcat:
            max-wait: 10000
            max-active: 50
            test-on-borrow: true
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: dev
        password: dev
        virtualHost: /
        publisherConfirms: true
        publisherReturns: true

---
spring:
    profiles: test

---
spring:
    profiles: prod