server:
    port: 5020
    servlet:
        context-path: /v1
        session:
            timeout: 7200s
    tomcat:
        basedir: /data/logs/access
        accesslog:
            enabled: true
            pattern: '%t %a "%r" %s (%D ms)'

logging:
    level:
        root: info
    path: ./data/logs

spring:
    setvlet:
        multipart:
            max-file-size: 15M
    #支持通过CGLIB方式代理
    aop:
        proxy-target-class: true
    mail:
        host: smtp.mxhichina.com
        username:
        password:
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 25000

rabbitmq:
    exchanges:
        collection-topic:
            name: collection-topic
            type: topic
            durable: true
    queues:
        collection-in:
            name: collection-in
        collection-out:
            name: collection-out
    bindings:
        collection-topic:
            - collection-in
            - collection-out


---
spring:
    profiles: dev
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: dev
        password: dev
        virtualHost: /


---
spring:
    profiles: test

---
spring:
    profiles: prod