server:
    port: 5020
    servlet:
        context-path: /v1
        session:
            timeout: 7200s
    tomcat:
        basedir: /data/logs/access
        accesslog:
            enabled: true
            pattern: '%t %a "%r" %s (%D ms)'

logging:
    level:
        root: info
    path: /data/logs

spring:
    setvlet:
        multipart:
            max-file-size: 15M
    #支持通过CGLIB方式代理
    aop:
        proxy-target-class: true
    mail:
        host: smtp.mxhichina.com
        username:
        password:
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 25000

mybatis:
    typeAliasesPackage: com.cold.framework.dao.model
    mapperLocations: classpath:mapper/*Mapper.xml
    configLocation: classpath:mybatis-config.xml
    checkConfigLocation: true

mapper:
    not-empty: false
    identity: MYSQL
    mappers:
        - com.cold.framework.dao.util.ColdMapper

rabbitmq:
    exchanges:
        collection-topic:
            name: collection-topic
            type: topic
            durable: true
        warn-fanout:
            name: warn-fanout
            type: fanout
            durable: true
    queues:
        collection-in:
            name: collection-in
        collection-out:
            name: collection-out
        message:
            name: warn-sms
        email:
            name: warn-email
    bindings:
        collection-topic:
            - collection-in
            - collection-out
        warn-fanout:
            - warn-sms
            - warn-email

sms:
    type: feige
    feige:
        account:
        pwd:
        signId:
        sendUrl: http://api.feige.ee/SmsService/Send

---
spring:
    profiles: dev
    redis:
        host:
        port:
        database:
        password:
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: dev
        password: dev
        virtualHost: /
        publisherConfirms: true
        publisherReturns: true
    datasource:
        druid:
            # JDBC
            url: jdbc:mysql://127.0.0.1:3306/
            username:
            password:
            driver-class-name: com.mysql.cj.jdbc.Driver
            # connection pool
            initial-size: 0
            max-active: 60
            min-idle: 2
            max-wait: 5000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            validation-query: 'SELECT 1 FROM DUAL'
            validation-query-timeout: 1000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 6000
            min-evictable-idle-time-millis: 600000
            max-evictable-idle-time-millis: 25200000
            keep-alive: true
            fail-fast: true
            filters: mergeStat,wall,slf4j
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                reset-enable: false
                login-username: dev
                login-password: dev
                allow: 127.0.0.1
                deny: 192.0.0.1


---
spring:
    profiles: test

---
spring:
    profiles: prod